Есеп 1.1

In [1]:
class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau
        self.avtory = avtory

    def kitap_turaly_malimet(self):
        """Кітап туралы ақпаратты шығару"""
        print(f"Кітап: {self.atau}, Авторы: {self.avtory}")

my_book = Kitap("Абай жолы", "Мұхтар Әуезов")

my_book.kitap_turaly_malimet()


Кітап: Абай жолы, Авторы: Мұхтар Әуезов


Есеп 2.1

In [2]:
import numpy as np

arr_a = np.arange(1, 10)
print("arr_a:", arr_a)
print("arr_a shape:", arr_a.shape)
print("arr_a dtype:", arr_a.dtype)

arr_b = np.arange(1, 10).reshape(3, 3)
print("\narr_b:\n", arr_b)
print("arr_b shape:", arr_b.shape)
print("arr_b dtype:", arr_b.dtype)


arr_a: [1 2 3 4 5 6 7 8 9]
arr_a shape: (9,)
arr_a dtype: int64

arr_b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_b shape: (3, 3)
arr_b dtype: int64


Есеп 3.1

In [3]:
import numpy as np

np.random.seed(0)
vec1 = np.random.randint(1, 11, size=5)
vec2 = np.random.randint(1, 11, size=5)

print("vec1:", vec1)
print("vec2:", vec2)

vec_sum = vec1 + vec2
print("vec1 + vec2:", vec_sum)

vec1_squared = vec1 ** 2
print("vec1 ** 2:", vec1_squared)

vec1_mean = vec1.mean()
vec1_max = vec1.max()
print("vec1 орташа мәні:", vec1_mean)
print("vec1 максимум мәні:", vec1_max)


vec1: [6 1 4 4 8]
vec2: [10  4  6  3  5]
vec1 + vec2: [16  5 10  7 13]
vec1 ** 2: [36  1 16 16 64]
vec1 орташа мәні: 4.6
vec1 максимум мәні: 8
